import sqlite3
from typing import List, Dict

DB_PATH = "skillvoice.db"

def init_db():
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # Companies table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS companies (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL,
            industry TEXT
        )
    """)
    
    # Users table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            phone TEXT UNIQUE,
            name TEXT,
            age INTEGER,
            gender TEXT,
            state TEXT,
            district TEXT,
            preferred_language TEXT,
            company_id INTEGER,
            employee_id TEXT UNIQUE,
            password TEXT,
            role TEXT,
            trade_domain TEXT,
            needs_diagnostic BOOLEAN DEFAULT FALSE,
            streak_days INTEGER DEFAULT 0,
            last_login_date TEXT,
            FOREIGN KEY(company_id) REFERENCES companies(id)
        )
    """)
    
    # Course Modules table (mock syllabus progress)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS course_modules (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER,
            module_id TEXT,
            title TEXT,
            is_completed BOOLEAN DEFAULT FALSE,
            FOREIGN KEY(user_id) REFERENCES users(id)
        )
    """)
    
    # Assessments table (for cooldowns and score tracking)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS assessments (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER,
            score INTEGER,
            date_taken TEXT,
            passed BOOLEAN,
            next_eligible_date TEXT,
            weak_topics TEXT,
            FOREIGN KEY(user_id) REFERENCES users(id)
        )
    """)
    
    # Learning Paths table (generated by AI for business)
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS learning_paths (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            user_id INTEGER,
            skill_gaps TEXT,
            curriculum_json TEXT,
            FOREIGN KEY(user_id) REFERENCES users(id)
        )
    """)
    
    # Certificates table
    cursor.execute("""
        CREATE TABLE IF NOT EXISTS certificates (
            id TEXT PRIMARY KEY,
            user_id INTEGER,
            trade TEXT,
            language TEXT,
            score INTEGER,
            date_certified TEXT,
            FOREIGN KEY(user_id) REFERENCES users(id)
        )
    """)
    
    conn.commit()
    conn.close()

def execute_query(query: str, params: tuple = ()) -> List[Dict]:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    cursor.execute(query, params)
    
    if query.strip().upper().startswith(("INSERT", "UPDATE", "DELETE")):
        conn.commit()
        last_id = cursor.lastrowid
        conn.close()
        return [{"lastrowid": last_id}]
    else:
        results = [dict(row) for row in cursor.fetchall()]
        conn.close()
        return results

init_db()

